### ISSUE TITLE
Guia de Instalación / servidores secundarios

### ISSUE THREAD

**Issue by macarthuror** [acrogenesis/API-Codigos-Postales#22]
Buen día,

Más que un problema, en realidad es una idea.

Mi propuesta es que se haga una guia de instalación de esta aplicación en otros servidores, para que externos podamos instalarlo.

Esto es para que las personas podamos crear servidores secundarios en caso de que el principal se caiga y compartir las ligas para que las personas sigan usando la API.

Gracias

**Comment by acrogenesis** [comment]
Pues para subirlo a heroku esta muy fácil, básicamente es solo darle push y correr las migraciones.

**Comment by acrogenesis** [comment]
Me falto agregar que como addons ocupas una base de datos postgres, Memcached y Heroku Scheduler para correr `rake sepomex:update` con la frecuencia deseada
