### ISSUE TITLE
App esta caida

### ISSUE THREAD

**Issue by oskyGomez** [acrogenesis/API-Codigos-Postales#28]
L aplicación marca crash en heroku. 

![image](https://user-images.githubusercontent.com/18534226/67873934-da6eb580-faf9-11e9-95e4-ce22866e3f95.png)

**Comment by acrogenesis** [comment]
La aplicación se apaga cuando se le acaban las horas gratis de heroku. Ya subí unas instrucciones para que lo puedas tener en heroku fácilmente.
