### ISSUE TITLE
Correr migracion 

### ISSUE THREAD

**Issue by dssd-nueve3** [acrogenesis/API-Codigos-Postales#29]
Hola como corro las migraciones desde heroku?

**Comment by dssd-nueve3** [comment]
I'm clonning your app into heroku but its not working.. I ran the migration and the rake alone but it does not seem to work: An unhandled lowlevel error occurred. The application logs may have details.

**Comment by acrogenesis** [comment]
Ya subi una nueva versión donde arreglo el tema de las migraciones. Puedes actualizarlo e intentar de nuevo.

**Comment by dssd-nueve3** [comment]
Gracias Adrian ya estoy actualizando la base de datos….

**Comment by dssd-nueve3** [comment]
ya actualizo pero no trae los municipios colonia y estado.
 {
"codigo_postal": "64600",
"municipio": "",
"estado": "",
"colonias": []
}

**Comment by acrogenesis** [comment]
Si ya lo habías corrido antes debe ser por el cache de memcache. Hay que darle clear.

**Comment by dssd-nueve3** [comment]
estoy intentando con heroku run --app YOUR_APP_NAME rails runner -e production Rails.cache.clear pero no me funciona y no encuentro como hacer flush del memchached

**Comment by dssd-nueve3** [comment]
ya quedo. es necesario instalar el menchached como Add on? y si es cual de los dos usa tu aplicación? MemCachier o memchached cloud

**Comment by leonardovz** [comment]
Soy yo o ya dejo de funcionar?

**Comment by acrogenesis** [comment]
Estoy usando memcached cloud no es necesario mas si hace que funcione más rápido

**Comment by acrogenesis** [comment]
> Soy yo o ya dejo de funcionar?

@leonardovz tu pregunta tiene algo que ver con correr las migraciones?
