### ISSUE TITLE
PG::InsufficientPrivilege: ERROR:  permission denied for table codigos_postales

### ISSUE THREAD

**Issue by antoniom7** [acrogenesis/API-Codigos-Postales#38]
Hola.
Estoy tratando de actualizar los códigos postales pero arroja un error de permisos, revisando veo que el número de registros esta excediendo al de filas:
Rows:                  140863/10000 (Write access revoked).

¿Es necesario modificar algo de mi lado?

Saludos

**Comment by acrogenesis** [comment]
Hola Antonio, ese error es de heroku postgres. Significa que estas excediendo el uso de la base de datos gratis de ellos. Te dan hasta 10,000 filas en la base de datos de forma gratuita, tienes que cambiar de proveedor de base de datos o pagar el upgrade para que ya sea en base a gigabytes. O puedes usar https://rapidapi.com/acrogenesis/api/mexico-zip-codes que ofrece 50 peticiones gratis. Mas ya no tienes que hostear tu el API
